#!/usr/bin/env bash
#  Bash script that displays numbers from 1 to 100:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

for a in {1..100}; 
do
    if (( a % 3 == 0 )) && (( a % 5 == 0 )); then
        echo "Fizz"
    elif (( a % 5 == 0 )); then
        echo "Buzz"
    elif (( a % 3 == 0 )); then
        echo "FizzBuzz"
    else
        echo "$a"
    fi
done
