#!/usr/bin/env bash
# script displays the time for 12 hours and 59 minutes:
#  display hours from 0 to 12
#  display minutes from 1 to 59

hour=0
minutes=1
echo "Hour: $hour"
while [ $minutes -le 59 ]; do
    echo "$minutes"
    minutes=$((minutes+1))
    if [ $minutes -eq 60 ]; then
        hour=$((hour+1))
        echo "Hour: $hour"
        minutes=1
    fi
    if [ $hour -eq 12 ]; then
        hour=1
    fi
done
